### ISSUE TITLE
Incorrect behaviour when passing arguments

### ISSUE THREAD

**Issue by niekcandaele** [chabad360/htmlproofer#4] opened 2020-02-01 13:42 UTC
I'm not sure if I'm doing something wrong or if this is a bug in the image.

In my local terminal, I have this command `htmlproofer --url-ignore "/(docs/edit/master)/" --check-html  docs/.vuepress/dist`. This works and htmlproofer does not return any errors.

In the actions config, I have this

```
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./docs/.vuepress/dist"
          arguments: --url-ignore "/(docs/edit/master)/" --check-html
```

However, it seems that the `--url-ignore "/(docs/edit/master)/"` argument does not get passed correctly. --check-html does work correctly.

An example action log is here: https://github.com/CatalysmsServerManager/docs/pull/82/checks?check_run_id=420831082

Thanks for creating this action, any guidance on this issue is very much appreciated :)

**Comment by chabad360** [comment] 2020-02-02 00:03
I believe the issue is a lack of quotes.

Try this:

```yaml
arguments: '--url-ignore "/(docs/edit/master)/" --check-html'
```

**Comment by niekcandaele** [comment] 2020-02-02 01:34
Thanks for replying. I actually tried a bunch of combinations with quotes as well :smile: 

I've got a PR open with a failing build right now to test with
https://github.com/CatalysmsServerManager/docs/pull/85

Locally, I run `htmlproofer --url-ignore "/(docs/edit/master)/"  docs/.vuepress/dist` which works. The same command doesn't work in the action.

In the actions log, I see `Running ["HtmlCheck", "LinkCheck", "ImageCheck", "ScriptCheck"] on ["./docs/.vuepress/dist"] on *.html... `

So the html check argument seems to go through ok

**Comment by chabad360** [comment] 2020-02-02 04:10
I'll have a look this week.

**Comment by chabad360** [comment] 2020-02-04 03:04
I hope this works, if it doesn't reopen.

**Comment by niekcandaele** [comment] 2020-02-06 22:45
Hello

Thanks for looking into this, I'm afraid it's not resolved yet though.
I've added a new commit to the above mentioned PR but the html proofer check still fails

**Comment by niekcandaele** [comment] 2020-02-06 22:46
Maybe I'm blind but I don't see a way to reopen this so I'll tag you instead :smile: 

@chabad360

**Comment by chabad360** [comment] 2020-02-17 05:35
@niekcandaele can you paste the output of `htmlproofer --url-ignore "/(docs/edit/master)/" --check-html docs/.vuepress/dist` when run in your terminal?

**Comment by niekcandaele** [comment] 2020-02-17 19:20
So another link has broken since, but this is a good example to show the url-ignore option I suppose :smile: 

In the first one, the new broken link is reported and the old one is correctly ignored. In the second (without the url-ignore argument) both links are reported


```
catalysm@metis ~/code/CSMM/docs  htmlproofer --url-ignore "/(docs/edit/master)/" --check-html docs/.vuepress/dist
Running ["ScriptCheck", "ImageCheck", "HtmlCheck", "LinkCheck"] on ["docs/.vuepress/dist"] on *.html... 


Checking 47 external links...
Ran on 37 files!


- docs/.vuepress/dist/en/CPM/index.html
  *  External link https://github.com/Prisma501/CSMM-Patrons-Mod/releases failed: 404 No error
htmlproofer 3.15.1 | Error:  HTML-Proofer found 1 failure!
```

```
catalysm@metis ~/code/CSMM/docs htmlproofer --check-html docs/.vuepress/dist
Running ["ScriptCheck", "ImageCheck", "HtmlCheck", "LinkCheck"] on ["docs/.vuepress/dist"] on *.html... 


Checking 82 external links...
Ran on 37 files!


- docs/.vuepress/dist/en/CPM/index.html
  *  External link https://github.com/Prisma501/CSMM-Patrons-Mod/releases failed: 404 No error
- docs/.vuepress/dist/en/CSMM/test-htmlproofer.html
  *  External link https://github.com/CatalysmsServerManager/docs/edit/master/docs/en/CSMM/test-htmlproofer.md failed: 404 No error
htmlproofer 3.15.1 | Error:  HTML-Proofer found 2 failures!
```

Thanks for looking into this!

**Comment by chabad360** [comment] 2020-02-20 15:23
This should be fixed now (actually), if it's still broken, simply comment.

**Closed as completed** 2020-02-20 15:23 UTC
